version: '3.8'
services:
  bot:
    build: .
    container_name: telegram_rp_bot
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:latest
    container_name: telegram_rp_bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

  mongo-express:
    image: mongo-express:latest
    container_name: telegram_rp_bot_mongo_express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - internal

volumes:
  mongo_data:

networks:
  internal:
    driver: bridge
