version: "3.8"
services:
  bot:
    restart: always
    container_name: telegram_rp_bot
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:latest
    restart: always
    container_name: telegram_rp_bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

volumes:
  mongo_data:

networks:
  internal:
    driver: bridge
