version: '3.8'
services:
  bot:
    build: .
    container_name: telegram_rp_bot
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: telegram_rp_bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:${DB_PORT}:27017"

volumes:
  mongo_data:
