version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: telegram_rp_bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:${DB_PORT}:27017"
    networks:
      - localnet

volumes:
  mongo_data:

networks:
  localnet:
    driver: bridge
