AI:
  TextGeneration:
    temperature: 0.7,
    max_tokens: 1000,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    request_timeout: 60.0,
    Models:
      gpt-3.5-turbo-16k:
        type: chat_completion
        rate:
          input_token_price: 1
          output_token_price: 2

      gpt-4:
        type: chat_completion
        rate:
          input_token_price: 5
          output_token_price: 10


  ImageProcessing:
    image_size: "512x512"
