AIConfig:
  TextGeneration:
    temperature: 0.7
    max_tokens: 1000
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    request_timeout: 60.0
    Models:
      gpt-4:
        name: "gpt-4"
        rate:
          input_token_price: 5
          output_token_price: 10

      gpt-4o:
        name: "gpt-4o"
        default: true
        rate:
          input_token_price: 5
          output_token_price: 10

      gpt-4o-mini:
        name: "gpt-4o-mini"
        rate:
          input_token_price: 1
          output_token_price: 2

  ImageProcessing:
    image_size: "512x512"
