models:
  gpt-3.5-turbo-16k:
    type: chat_completion
    rate:
      price_per_1000_input_tokens: 0.0015
      price_per_1000_output_tokens: 0.002

  gpt-4:
    type: chat_completion
    rate:
      price_per_1000_input_tokens: 0.03
      price_per_1000_output_tokens: 0.06
