name: Linting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Lint Python files
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest

      - name: Lint YAML files
        run: uv run yamllint .
